/**
 * vue-docgen-cli config — generates per-component reference partials
 * from SFC source. Output is consumed by Docusaurus pages via MDX import.
 *
 * Phase 1 spike: scoped to CnDataTable only. Once the output looks right,
 * Phase 3 expands the glob to all Cn* components.
 *
 * MDX-3 brace safety: `escapeMdxBraces()` runs over every generated
 * description / default cell to backslash-escape `{` and `}` characters
 * that aren't already inside backticks. Without this, prop defaults like
 * `'{name}'` or JSDoc examples mentioning `{appId}` would be parsed as
 * JSX expressions and crash the Docusaurus build.
 */

const path = require('path')

// Resolve from project root regardless of where vue-docgen-cli is invoked.
const REPO_ROOT = path.resolve(__dirname, '..')

/**
 * Make a JSDoc string safe inside MDX 3 markdown outside inline-code spans:
 *
 *   - `{` / `}` are escaped with a backslash so MDX doesn't read them as
 *     JSX expression delimiters (would throw `ReferenceError: <name> is
 *     not defined`).
 *   - `<` / `>` are HTML-entity-encoded so MDX doesn't read them as the
 *     start of a JSX element (would throw `Unexpected character` when a
 *     TS-style generic like `Array<{key, label}>` appears in a JSDoc
 *     description).
 *
 * Inside backticks (single inline-code spans) the content is left as-is —
 * MDX treats it as code and skips JSX/expression parsing.
 */
function escapeMdxBraces(text) {
  if (!text) return text
  let out = ''
  let inCode = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (c === '`') {
      inCode = !inCode
      out += c
    } else if (!inCode && (c === '{' || c === '}')) {
      out += '\\' + c
    } else if (!inCode && c === '<') {
      out += '&lt;'
    } else if (!inCode && c === '>') {
      out += '&gt;'
    } else {
      out += c
    }
  }
  return out
}

module.exports = {
  componentsRoot: path.join(REPO_ROOT, 'src/components'),
  // Phase 3: walk every Cn*/Cn*.vue. The CI freshness gate (`git diff
  // --exit-code docs/components/_generated/`) treats this as the
  // authoritative set, so any new Cn* component will land its own
  // partial in the same PR.
  components: 'Cn*/Cn*.vue',
  outDir: path.join(REPO_ROOT, 'docs/components/_generated'),

  // Each component gets its own .md file.
  getDestFile: (file, config) => {
    const componentName = path.basename(file, '.vue')
    return path.join(config.outDir, `${componentName}.md`)
  },

  templates: {
    // Top-level component template. Reference tables only — no top-level H1
    // and no narrative description. The Docusaurus page that imports this
    // partial owns the narrative and headings; this partial slots into a
    // ## Reference section on that page.
    component(renderedUsage, doc, config, fileName, requiresMd, subComponent) {
      const { displayName, props, events, slots, methods } = doc
      const stamp = `<!-- AUTO-GENERATED by vue-docgen-cli — do not edit. Source: src/components/${displayName}/${displayName}.vue -->`
      const blocks = [stamp]

      if (props && props.length) {
        blocks.push('### Props')
        blocks.push(renderProps(props))
      }

      if (events && events.length) {
        blocks.push('### Events')
        blocks.push(renderEvents(events))
      }

      if (slots && slots.length) {
        blocks.push('### Slots')
        blocks.push(renderSlots(slots))
      }

      if (methods && methods.length) {
        blocks.push('### Methods')
        blocks.push(renderMethods(methods))
      }

      return blocks.join('\n\n') + '\n'
    },
  },
}

/**
 * Markdown-table-cell-safe text: collapse newlines, escape pipes, escape MDX braces.
 */
function cell(text) {
  return escapeMdxBraces(text || '')
    .replace(/\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim()
}

/**
 * Some SFCs in the codebase use `@event eventName Description text on same line`
 * (non-standard JSDoc). vue-docgen-api treats the whole "eventName Description"
 * as the event's `name`. Split on first whitespace so we get a clean name +
 * description.
 */
function splitMashedEventName(rawName) {
  const m = rawName.match(/^([\w-]+)\s+(.+)$/s)
  if (m) return { name: m[1], extraDesc: m[2] }
  return { name: rawName, extraDesc: '' }
}

function renderProps(props) {
  const rows = props.map(p => {
    const name = `\`${p.name}\``
    const type = p.type ? `\`${p.type.name}\`` : '—'
    const required = p.required ? '✓' : ''
    const defaultValue = p.defaultValue ? `\`${cell(p.defaultValue.value)}\`` : '—'
    const desc = cell(p.description)
    return `| ${name} | ${type} | ${required} | ${defaultValue} | ${desc} |`
  })
  return [
    '| Name | Type | Required | Default | Description |',
    '|------|------|----------|---------|-------------|',
    ...rows,
  ].join('\n')
}

function renderEvents(events) {
  // Dedupe by clean name — vue-docgen-api emits a separate entry for each
  // template `$emit` site as well as the JSDoc tag. Keep the entry with the
  // richer description.
  const byName = new Map()
  for (const e of events) {
    const { name: cleanName, extraDesc } = splitMashedEventName(e.name)
    const desc = [e.description, extraDesc].filter(Boolean).join(' — ')
    const existing = byName.get(cleanName)
    if (!existing || (desc && desc.length > (existing.desc || '').length)) {
      byName.set(cleanName, { event: e, desc })
    }
  }
  const rows = [...byName.entries()].map(([cleanName, { event: e, desc }]) => {
    const name = `\`${cleanName}\``
    const payload = e.properties && e.properties.length
      ? e.properties.map(p => `\`${p.type.names ? p.type.names.join('\\|') : p.type.name}\``).join(', ')
      : '—'
    return `| ${name} | ${payload} | ${cell(desc)} |`
  })
  return [
    '| Name | Payload | Description |',
    '|------|---------|-------------|',
    ...rows,
  ].join('\n')
}

function renderSlots(slots) {
  // vue-docgen-api sometimes returns dynamic slot expressions (e.g.
  // "'column-' + col.key") as the slot name. Wrap in code; consumers can
  // override with hand-written narrative if a friendlier label is needed.
  const rows = slots.map(s => {
    const name = `\`${s.name}\``
    const desc = cell(s.description)
    const bindings = s.bindings && s.bindings.length
      ? s.bindings.map(b => `\`${b.name}\``).join(', ')
      : '—'
    return `| ${name} | ${bindings} | ${desc} |`
  })
  return [
    '| Name | Bindings | Description |',
    '|------|----------|-------------|',
    ...rows,
  ].join('\n')
}

function renderMethods(methods) {
  const rows = methods.map(m => {
    const name = `\`${m.name}\``
    const desc = cell(m.description)
    return `| ${name} | ${desc} |`
  })
  return [
    '| Name | Description |',
    '|------|-------------|',
    ...rows,
  ].join('\n')
}
