/**
 * Phase 5 of unify-component-docs — explicit IA. The sidebar groups docs
 * by reader intent, not by source-folder layout:
 *
 *   - Getting Started     onboarding (single page)
 *   - Architecture        how the library is built (concept-first)
 *   - Building Apps       how to ship something with it (task-first)
 *   - Components          per-component reference (43 pages, narrative + Playground + auto-gen)
 *   - Composables         use* hooks (8 pages)
 *   - Utilities           pure-function helpers (18 pages, excludes the composables/ subdir)
 *   - Design Tokens       Nextcloud CSS variables every Cn* component reads
 *
 * Why explicit-not-autogenerated for Utilities:
 *   `docs/utilities/composables/` lives inside `docs/utilities/` for legacy
 *   reasons. Pure autogen on `dirName: 'utilities'` would nest composables
 *   under Utilities, duplicating them with the top-level Composables group.
 *   Listing utility files explicitly here (and only here) gives the clean
 *   IA without moving files. Adding a new utility = one line in this file.
 *
 * Note about i18n:
 *   `docs/i18n/` holds Docusaurus locale JSON, not user content. The actual
 *   i18n guide is at docs/integrations/i18n.md and is reachable via
 *   Building Apps > Integrations. No separate top-level category.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'getting-started',

    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'generated-index', slug: '/architecture' },
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },

    {
      type: 'category',
      label: 'Building Apps',
      link: {
        type: 'generated-index',
        slug: '/building-apps',
        description:
          'Task-oriented guides for shipping a Conduction Nextcloud app with @conduction/nextcloud-vue: page layouts, cards, integrations (incl. i18n), the object store, and the JSON manifest renderer.',
      },
      items: [
        {
          type: 'category',
          label: 'Layouts',
          link: { type: 'doc', id: 'layouts/index' },
          items: [{ type: 'autogenerated', dirName: 'layouts' }],
        },
        {
          type: 'category',
          label: 'Cards',
          link: { type: 'doc', id: 'cards/index' },
          items: [{ type: 'autogenerated', dirName: 'cards' }],
        },
        {
          type: 'category',
          label: 'Integrations',
          // Integrations covers OpenRegister, NL Design System, the
          // ecosystem overview, AND the i18n guide (docs/integrations/i18n.md).
          // There is no separate top-level i18n folder of docs — `docs/i18n/`
          // holds Docusaurus locale JSON, not user content.
          items: [{ type: 'autogenerated', dirName: 'integrations' }],
        },
        {
          type: 'category',
          label: 'Store',
          items: [{ type: 'autogenerated', dirName: 'store' }],
        },
        'migrating-to-manifest',
      ],
    },

    {
      type: 'category',
      label: 'Components',
      link: { type: 'doc', id: 'components/index' },
      items: [{ type: 'autogenerated', dirName: 'components' }],
    },

    {
      type: 'category',
      label: 'Composables',
      link: { type: 'doc', id: 'utilities/composables/index' },
      items: [{ type: 'autogenerated', dirName: 'utilities/composables' }],
    },

    {
      type: 'category',
      label: 'Utilities',
      link: { type: 'doc', id: 'utilities/index' },
      items: [
        'utilities/build-headers',
        'utilities/build-query-string',
        'utilities/columns-from-schema',
        'utilities/default-page-types',
        'utilities/fields-from-schema',
        'utilities/filter-widgets-by-visibility',
        'utilities/filters-from-schema',
        'utilities/format-value',
        'utilities/generic-error',
        'utilities/get-current-user-groups',
        'utilities/get-current-user-id',
        'utilities/is-widget-visible',
        'utilities/manifest-defs',
        'utilities/network-error',
        'utilities/parse-response-error',
        'utilities/reset-visibility-cache',
        'utilities/validate-manifest',
        'utilities/validate-value',
      ],
    },

    {
      type: 'category',
      label: 'Design Tokens',
      link: { type: 'doc', id: 'design-tokens/index' },
      items: [],
    },
  ],
}

module.exports = sidebars
